export const REGISTER_USER = 'REGISTER_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const MATERI_IS_LOADING = 'MATERI_IS_LOADING'
export const CREATE_MATERI_SUCCESS = 'CREATE_MATERI_SUCCESS'
export const CREATE_MATERI_FAILED = 'CREATE_MATERI_FAILED'
export const FETCH_MATERIES = 'FETCH_MATERIES'